### PR TITLE
Add netstandard2.0 support instead of only net472-windows and net48-w…

### PR DESCRIPTION
**Pull request by gotty1337**
Hi :)
Would you also consider to add netstandard2.0 to support also net471 and other frameworks that work with netstandard2.0? I am also using LibUsbDotNet on Linux and this cause the following compilation errors, if I want to us WinUsb on WIN32 and LibUsb on Linux: "NU1701 - Package 'Nefarius.Drivers.WinUSB 5.3.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net10.0'. This package may not be fully compatible with your project."

## Summary by CodeRabbit

* **Compatibility**
  * Added support for applications targeting .NET Standard 2.0.
  * Removed direct build targets for .NET Framework 4.7.2 and 4.8.

### CODE REVIEW

**Comment by nefarius** [comment]
I'd rather have it **added** than replaced; I still have active users of .NET Framework 4.7.2 and 4.8 so explicit support is desired.

**Comment by nefarius** [comment]
Thank you for the report and the initial change, @gotty1337.

I'd rather add `netstandard2.0` than replace the explicit .NET Framework assets, since `net472` and `net48` consumers are still active. I opened #58 as the replacement: it keeps those Framework targets, adds `netstandard2.0` plus `net10.0-windows`, documents the Windows-only runtime, and covers consumer restore/build for `net471`, `net472`, `net48`, `net10.0`, and `net10.0-windows`.

Closing this PR in favor of #58.

**Comment by nefarius** [comment]
@gotty1337 I published `v5.4.0-pre001` please see if that solves your case once it is indexed. Cheers

**Comment by gotty1337** [comment]
@nefarius: Thanks a lot! :)
